"""
Django settings for MoneyMind project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
# from environ import Env
import os

# env = Env()
# env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p9xvht$v_f-57#)y8m3bx_7zy44*ph^@&cte@i^-b(tr+sea2k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',

    # เพิ่ม
    'django_cleanup.apps.CleanupConfig',

    # แอพ
    "expenses",

    # Login
    'django.contrib.sites',
    'allauth',
    'allauth.account',  
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# login
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'dashboard'  
LOGOUT_REDIRECT_URL = 'account_login'

#  ไม่สร้างบัญชี Google ซ้อนทับ
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_PREVENT_ENUMERATION = False

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# อนุญาตให้เชื่อมต่ออัตโนมัติถ้าอีเมลตรงกัน
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

ACCOUNT_EMAIL_VERIFICATION = "none"
# ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_REQUIRED = True   

# บังคับว่า 1 อีเมล ต้องมีแค่ 1 บัญชีเท่านั้น ห้ามซ้ำเด็ดขาด
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# ถ้าอีเมลจาก Google ตรงกับอีเมลในระบบ 
SOCIALACCOUNT_ADAPTER = 'expenses.adapter.MySocialAccountAdapter'
ACCOUNT_ADAPTER = 'expenses.adapter.MyAccountAdapter'
# ACCOUNT_ADAPTER = 'expenses.adapter.CustomAccountAdapter'

LOGGING = { 
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # ส่วนนี้จะ Print ข้อมูลดิบของ Allauth ออกมา
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',  # ระดับละเอียดสุด (เห็นทุกขั้นตอน)
        },
        # ส่วนนี้จะ Print Error ของ Django request (เช่น 500 Error)
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
    },
}

# 'APP': {
#             'client_id': env('OAUTH_GOOGLE_CLIENT_ID'),
#             'secret': env('OAUTH_GOOGLE_SECRET'),
#         },
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # login
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "MoneyMind.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MoneyMind.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
