# Generated by Django 6.0 on 2026-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_trainingdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
