# Generated by Django 6.0 on 2026-01-21 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="คำค้นหา (Keyword)"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.category",
                        verbose_name="หมวดหมู่ที่คู่กัน",
                    ),
                ),
            ],
        ),
    ]
