# Generated by Django 6.0 on 2026-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_categorykeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
