# Generated by Django 6.0 on 2026-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0008_usercategorypreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="secondary", max_length=20, verbose_name="สี"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="bi-tags-fill", max_length=50, verbose_name="ไอคอน"
            ),
        ),
    ]
